version: 2.1
jobs:
  build-and-deploy:
    docker:
      - image: circleci/node:14
    steps:
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t orozali/docker-tutorial:latest .
            echo "$DOCKERHUB_PASSWORD" | docker login --username orozali --password-stdin
            docker push orozali/docker-tutorial:latest
      - run:
          name: Install SSH And Configure
          command: |
            echo $SSH_PRIVATE_KEY | base64 --decode > ./privateKey.pem
            chmod 400 privateKey.pem
      - run:
          name: Pull Image and Deploy
          command: |
            ssh -o "StrictHostKeyChecking=no" -i ./privateKey.pem ubuntu@$HOST
            docker pull orozali/docker-tutorial:latest
            docker run -d -p 8088:8088 orozali/docker-tutorial:latest
workflows:
  deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: main