CREATE TABLE Student(
id int primary key generated by default as identity,
name varchar,
surname varchar,
student_number varchar,
password varchar,
email varchar,
tel_number int,
place_of_birth varchar,
father_name varchar,
mother_name varchar,
nationality varchar,
faculty varchar,
profession varchar,
role varchar
);

INSERT INTO Student values
                        (100,'Orozali','Iliazov','2004.01031','$2a$10$Nf2oJ883JhX/70ZBLLu/0.7M/EoTahZcedap4OliEck/3FkPNA9wK'
                        ,'oroz@gmail.com',343,'sdf','Uluk','Laili','kyrgyz','IT','IT','ROLE_ADMIN');